hydra:
  run:
    dir: ./

train_file: /home/share/jiaofangkai/wiki_erica_path/v5/union/train_distant.path_v5.train.0.pkl
dev_file: /home/share/jiaofangkai/wiki_erica_path/v5/union/train_distant.path_v5.dev.pkl
test_file:

# Model
model:
  _target_: models.roberta_baseline.RobertaForMultipleChoiceForPreTrain.from_pretrained
  mlp_hidden_size: 2048  # For large model.

# Data loading
read_tensor:
  _target_: datasets.wiki_entity_path_v6.convert_examples_into_features
  max_neg_num: 3
  aug_num: 2
  max_seq_length: 384
  shuffle_context: True
  min_rep_num: 2
  geo_p: 0.4
  num_workers: 64

extended_vocab:

# Data collator
collator:
  _target_: datasets.wiki_entity_path_v5.WikiPathDatasetCollator
  max_seq_length: 384
  tokenizer: pretrained-models/roberta-large
  mlm_probability: 0.15

# Dataloader
num_workers: 4
prefetch_factor: 2

model_name_or_path: pretrained-models/roberta-large
pretrain:

output_dir: experiments/roberta.large.wiki_erica_path_v6_0.1.0.2080Ti.ds

do_train: True
evaluate_during_training: True

do_eval: False
eval_sub_path: "checkpoint-1400"

do_preprocess: True

# Training hyper-parameters
# ============= For base model ==========
#per_gpu_train_batch_size: 4
#per_gpu_eval_batch_size: 4
#learning_rate: 1e-4
# ============= For large model =============
per_gpu_train_batch_size: 1
per_gpu_eval_batch_size: 1
learning_rate: 1e-4
gradient_accumulation_steps: 1024
num_train_epochs: 1
max_steps: 0
weight_decay: 0.01

# Optimizer
#optimizer: lamb
#use_nvlamb: True

logging_steps: 1
save_steps: 50
eval_steps: 50
no_cuda: False
seed: 42
local_rank: -1
#fp16: True
#fp16_opt_level: O1

# fairscale.FullyShardedDDP
reshard_after_forward: False
cpu_offload: False
move_grads_to_cpu: False
move_params_to_cpu: False

# Temporary variables
n_gpu:
device:
train_batch_size:
eval_batch_size:


# DeepSpeed
deepspeed_config: conf/deepspeed/defaults.json
deepspeed: True
num_gpus: 2
deepspeed_transformer_kernel:
