hydra:
  run:
    dir: ./

train_file: reclor_data/train.json
dev_file: reclor_data/val.json
test_file: reclor_data/test.json

# Model
model:
#  _target_: models.roberta_baseline.RobertaForMultipleChoiceForZeroShot.from_pretrained
  _target_: models.roberta_baseline.RobertaForMultipleChoicePrompt.from_pretrained
  mlp_hidden_size: 2048
  fs_checkpoint: False
  fs_checkpoint_offload_to_cpu: False
  fs_checkpoint_maintain_forward_counter: False
  freeze_encoder: True
#  freeze_pooler: True
  freeze_pooler: False
  hidden_dropout_prob: 0.0
  attention_probs_dropout_prob: 0.0

# Data loading
read_tensor:
  _target_: dataset.reclor_sentence_prefix.convert_examples_into_features
  max_seq_length: 256
  num_workers: 2
  token_num: 10
  add_prefix_pos: True

extended_vocab: ${read_tensor.token_num}

# Data collator
collator:
#  _target_: dataset.collators.ReClorSentenceCollator
  _target_: dataset.collators.ReClorSentenceCollatorPrefixPos

# Dataloader
num_workers: 4
prefetch_factor: 2

# Wiki path pretrain v8.2
model_name_or_path: experiments/roberta.large.wiki_erica_path_v7_v8.2.2.1aug.ctx.1k.2080Ti/checkpoint-500

pretrain:

#output_dir: experiments/roberta.large.path.v8.2.2.1aug.ctx.1k.cp500.kb.fz_pooler.d0.pm1.0.w1.2080Ti.s${seed}
output_dir: experiments/roberta.large.path.v8.2.2.1aug.ctx.1k.cp500.kb.d0.pm1.1.w1.2080Ti.s${seed}

#output_dir: experiments/roberta.large.path.v8.2.2.1aug.ctx.1k.cp500.kb.fz_pooler.d0.pm1.0.w1.TitanXP.s${seed}


do_train: True
#do_train: False
evaluate_during_training: True

do_eval: False
#do_eval: True
eval_sub_path: checkpoint-1300

# Training hyper-parameters
per_gpu_train_batch_size: 3
per_gpu_eval_batch_size: 3
#learning_rate: 1e-5
#learning_rate: 1.5e-5
#learning_rate: 2e-5
#learning_rate: 1e-3
learning_rate: 1e-4
gradient_accumulation_steps: 8
weight_decay: 0.01
adam_epsilon: 1e-6
adam_betas: "(0.9, 0.98)"
max_grad_norm: 0.0
num_train_epochs: 10
max_steps: 0
warmup_proportion: 0.1
warmup_steps: 0


logging_steps: 5
save_steps: 100
eval_steps: 100
no_cuda: False
seed: 42
local_rank: -1
fp16: True
fp16_opt_level: O1

# fairscale.FullyShardedDDP
reshard_after_forward: False
cpu_offload: False
move_grads_to_cpu: False
move_params_to_cpu: False

# Temporary variables
n_gpu:
device:
train_batch_size:
eval_batch_size:
world_size:
