hydra:
  run:
    dir: ./

train_file: reclor_data/train.json
dev_file: reclor_data/val.json
test_file: reclor_data/test.json

# Model
model:
  _target_: models.deberta.DebertaV2ForMultipleChoice.from_pretrained
  num_labels: 1

# Data loading
read_tensor:
  _target_: dataset.reclor_sentence.convert_examples_into_features
  max_seq_length: 256
  num_workers: 2

#extended_vocab: 4

# Data collator
collator:
  _target_: dataset.collators.ReClorSentenceCollator

# Dataloader
num_workers: 4
prefetch_factor: 2

#model_name_or_path: pretrained-models/roberta-large
#model_name_or_path: pretrained-models/albert-xxlarge-v2
#model_name_or_path: pretrained-models/roberta-large-mnli
#model_name_or_path: pretrained-models/roberta-base
#model_name_or_path: pretrained-models/ERICA_pretrained/pretrained-models/roberta_ep_rp_hf
model_name_or_path: pretrained-models/deberta-v2-xlarge

# Wiki path pretrain v8.0
#model_name_or_path: experiments/roberta.large.wiki_erica_path_v8.1.1.V100-16g/checkpoint-500
#model_name_or_path: experiments/roberta.large.wiki_erica_path_v8.1.1.2080Ti/checkpoint-500
#model_name_or_path: experiments/roberta.large.wiki_erica_path_v8.1.1.2080Ti/checkpoint-1000
#model_name_or_path: experiments/roberta.large.wiki_erica_path_v8.1.1.V100-16g/checkpoint-1000

# MultiNLI transfer learning test
#model_name_or_path: experiments/mnli.roberta.large.path.w2.v1.0/checkpoint-35000

pretrain:

#output_dir: experiments/roberta.large.wiki_erica_path_v8.1.1.cp500.2.0.TeslaT4
#output_dir: experiments/roberta.large.wiki_erica_path_v8.1.1.cp500.2.1.TitanXP
#output_dir: experiments/roberta.large.wiki_erica_path_v8.1.1.cp500.2.0.TitanXP

#output_dir: experiments/roberta.large.wiki_erica_path_v8.1.1.2080ti-cp500.2.0.2080Ti
#output_dir: experiments/roberta.large.wiki_erica_path_v8.1.1.2080ti-cp500.2.0.w1.2080Ti
#output_dir: experiments/roberta.large.wiki_erica_path_v8.1.1.2080ti-cp500.2.0.vanilla.2080Ti
#output_dir: experiments/roberta.large.wiki_erica_path_v8.1.1.2080ti-cp500.2.0.w4.2080Ti
#output_dir: experiments/roberta.large.wiki_erica_path_v8.1.1.2080ti-cp500.2.0.w4.Titan
#output_dir: experiments/roberta.large.wiki_erica_path_v8.1.1.2080ti-cp500.3.0.w4.2080Ti
#output_dir: experiments/roberta.large.wiki_erica_path_v8.1.1.2080ti-cp500.3.1.w4.2080Ti
#output_dir: experiments/roberta.large.wiki_erica_path_v8.1.1.2080ti-cp500.4.0.w4.2080Ti
#output_dir: experiments/roberta.large.wiki_erica_path_v8.1.1.2080ti-cp500.4.1.w3.2080Ti
#output_dir: experiments/roberta.large.wiki_erica_path_v8.1.1.2080ti-cp500.5.0.w4.2080Ti  # P-tuning
#output_dir: experiments/roberta.large.wiki_erica_path_v8.1.1.2080ti-cp500.2.0.norm.2080Ti
#output_dir: experiments/roberta.large.wiki_erica_path_v8.1.1.2080ti-cp1000.3.0.w4.2080Ti
#output_dir: experiments/roberta.large.wiki_erica_path_v8.1.1.2080ti-cp1000.2.0.2080Ti
#output_dir: experiments/roberta.large.wiki_erica_path_v8.1.1.2080ti-cp1000.2.0.w4.2080Ti

#output_dir: experiments/roberta.large.wiki_erica_path_v8.1.1.v100-cp1000.2.0.TitanXP
#output_dir: experiments/roberta.large.wiki_erica_path_v8.1.1.v100-cp1000.2.1.TitanXP

#output_dir: experiments/roberta.large.wiki_erica_path_v8.1.1.2080ti-cp500.2.1.w4.Titan

#output_dir: experiments/roberta.large.wiki_erica_path_v8.1.1.2080ti-cp500.2.0.w4.TeslaT4
#output_dir: experiments/roberta.large.wiki_erica_path_v8.1.1.2080ti-cp500.2.0.w4.TeslaT4.seed43
#output_dir: experiments/roberta.large.wiki_erica_path_v8.1.1.2080ti-cp500.2.0.w4.TeslaT4.seed44
#output_dir: experiments/roberta.large.wiki_erica_path_v8.1.1.2080ti-cp500.2.1.w4.TeslaT4
#output_dir: experiments/roberta.large.wiki_erica_path_v8.1.1.2080ti-cp500.2.2.w4.TeslaT4
#output_dir: experiments/roberta.large.wiki_erica_path_v8.1.1.2080ti-cp1000.2.0.w4.TeslaT4

# MultiNLI transfer
#output_dir: experiments/roberta.large.wiki_erica_path_v8.1.1.2080ti-cp500.mnli-cp35k.4.0.w4.2080Ti

# Baseline using MLM only pre-train
#output_dir: experiments/roberta.large.mlm.cp500.1.0.2080Ti

output_dir: experiments/deberta.v2.xlarge.w4.v1.0

do_train: True
#do_train: False
evaluate_during_training: True

do_eval: False
#do_eval: True
eval_sub_path: checkpoint-1200

# Training hyper-parameters
per_gpu_train_batch_size: 1
per_gpu_eval_batch_size: 1
learning_rate: 1e-5
#learning_rate: 8e-6
#learning_rate: 5e-6
#learning_rate: 2e-5
#gradient_accumulation_steps: 12
#gradient_accumulation_steps: 4
#gradient_accumulation_steps: 16
#gradient_accumulation_steps: 8
gradient_accumulation_steps: 6
#gradient_accumulation_steps: 2
weight_decay: 0.01
adam_epsilon: 1e-6
adam_betas: "(0.9, 0.98)"
max_grad_norm: 0.0
#max_grad_norm: 1.0
num_train_epochs: 10
#num_train_epochs: 14
#num_train_epochs: 5
max_steps: 0
warmup_proportion: 0.1
#warmup_proportion: 0.06
warmup_steps: 0


logging_steps: 5
save_steps: 100
eval_steps: 100
no_cuda: False
seed: 42
#seed: 43
#seed: 44
local_rank: -1
fp16: True
fp16_opt_level: O1

# fairscale.FullyShardedDDP
reshard_after_forward: False
cpu_offload: False
move_grads_to_cpu: False
move_params_to_cpu: False

# Temporary variables
n_gpu:
device:
train_batch_size:
eval_batch_size:
world_size:

# Nodes
note: "Running pre-training. If you need the resource urgently, feel free to contact me."
