hydra:
  run:
    dir: ./

train_file: reclor_data/train.json
dev_file: reclor_data/val.json
test_file: reclor_data/test.json

# Model
model:
#  _target_: models.albert_sent.AlbertSentenceMCQA.from_pretrained
  _target_: models.roberta_baseline.RobertaForMultipleChoice.from_pretrained

# Data loading
read_tensor:
  _target_: datasets.reclor_sentence.convert_examples_into_features
  max_seq_length: 256
  num_workers: 2

# Data collator
collator:
  _target_: datasets.data_collators.ReClorSentenceCollator

# Dataloader
num_workers: 4
prefetch_factor: 2


model_name_or_path: pretrained-models/roberta-base
pretrain:

output_dir: experiments/roberta.base.3.0

do_train: True
evaluate_during_training: True

# Training hyper-parameters
per_gpu_train_batch_size: 8
per_gpu_eval_batch_size: 8
learning_rate: 8e-6
gradient_accumulation_steps: 3
weight_decay: 0.01
adam_epsilon: 1e-6
adam_betas: "(0.9, 0.98)"
max_grad_norm: 0.0
num_train_epochs: 10
max_steps: 0
warmup_proportion: 0.1
warmup_steps: 0


logging_steps: 5
save_steps: 200
eval_steps: 200
no_cuda: False
seed: 42
local_rank: -1
fp16: True
fp16_opt_level: O1

# fairscale.FullyShardedDDP
reshard_after_forward: False
cpu_offload: False

# Temporary variables
n_gpu:
device:
train_batch_size:
eval_batch_size:
