hydra:
  run:
    dir: ./

train_file: reclor_data/train.json
dev_file: reclor_data/val.json
test_file: reclor_data/test.json

# Model
model:
  _target_: models.roberta_baseline.RobertaForMultipleChoiceForZeroShot.from_pretrained
  mlp_hidden_size: 2048  # For large model.
  fs_checkpoint: False
  fs_checkpoint_offload_to_cpu: False
  fs_checkpoint_maintain_forward_counter: False

# Data loading
read_tensor:
  _target_: datasets.reclor_sentence.convert_examples_into_features
  max_seq_length: 256
#  max_seq_length: 220
  num_workers: 2

extended_vocab:
#  _target_: datasets.wiki_entity_path.get_num_extended_tokens

# Data collator
collator:
  _target_: datasets.collators.ReClorSentenceCollator

# Dataloader
num_workers: 16
prefetch_factor: 2


#model_name_or_path: pretrained-models/roberta-large-mnli
model_name_or_path: pretrained-models/roberta-large
#model_name_or_path: pretrained-models/roberta-base

#model_name_or_path: experiments/roberta.large.wiki_erica_path_v8.1.1.2080Ti/checkpoint-500
#model_name_or_path: experiments/roberta.large.wiki_erica_path_v8.1.1.2080Ti/checkpoint-1000
pretrain:

#output_dir: experiments/roberta.large.wiki_erica_path_v8.1.1.V100-16g

#output_dir: experiments/roberta.large.wiki_erica_path_v8.rep6.1.0.v100-16g

output_dir: experiments/roberta.large.wiki_erica_path_v8.1.1.2080Ti

do_train: False
evaluate_during_training: True

do_eval: True
eval_sub_path: checkpoint-500

do_preprocess: False

# Training hyper-parameters
# ============= For base model ==========
#per_gpu_train_batch_size: 4
#per_gpu_eval_batch_size: 4
#learning_rate: 1e-4
# ============= For large model =============
per_gpu_train_batch_size: 1
per_gpu_eval_batch_size: 1
#per_gpu_train_batch_size: 2
#per_gpu_eval_batch_size: 2
learning_rate: 1e-4
gradient_accumulation_steps: 256
weight_decay: 0.01
adam_epsilon: 1e-6
adam_betas: "(0.9, 0.98)"
max_grad_norm: 5.0
num_train_epochs: 1
max_steps: 0
warmup_proportion: 0.1
warmup_steps: 0

# Optimizer
optimizer: lamb
use_nvlamb: True

logging_steps: 1
#save_steps: 50
#eval_steps: 50
save_steps: 100
eval_steps: 100
no_cuda: False
seed: 42
local_rank: -1
fp16: True
fp16_opt_level: O1

# fairscale.FullyShardedDDP
reshard_after_forward: False
cpu_offload: False
move_grads_to_cpu: False
move_params_to_cpu: False

# Temporary variables
n_gpu:
device:
train_batch_size:
eval_batch_size:
world_size:
