hydra:
  run:
    dir: ./

train_file: /home/share/jiaofangkai/wiki_erica_path/v7/union/train_distant.path_v7.train.0.pkl
dev_file: /home/share/jiaofangkai/wiki_erica_path/v7/union/train_distant.path_v7.dev.pkl
test_file:

# Model
model:
  _target_: models.deberta.DebertaV2ForMultipleChoicePreTrain.from_pretrained
  mlp_hidden_size: 3072  # For v2-xlarge

# Data loading
read_tensor:
  _target_: dataset.wiki_entity_path_v8_2.convert_examples_into_features
  max_neg_num: 3
  aug_num: 1
  max_seq_length: 256
  shuffle_context: True
  min_rep_num: 5
  geo_p: 0.4
  deduct_ratio: 1.0
  context_ratio: 1.0
  num_workers: 64

extended_vocab:
#  _target_: datasets.wiki_entity_path.get_num_extended_tokens

# Data collator
collator:
  _target_: dataset.wiki_entity_path_v8.WikiPathDatasetCollatorWithContext
  max_seq_length: 256
  tokenizer: pretrained-models/deberta-v2-xlarge
  mlm_probability: 0.15
  max_option_num: 4
  swap: True

# Dataloader
num_workers: 8
prefetch_factor: 2

model_name_or_path: pretrained-models/deberta-v2-xlarge
pretrain:

output_dir: experiments/albert.v2.xlarge.path.v7_v8.2.2.1aug.ctx.TeslaT4

do_train: Train
evaluate_during_training: True

do_eval: False
eval_sub_path:

do_preprocess: True

# Training hyper-parameters
# ============= For base model ==========
#per_gpu_train_batch_size: 4
#per_gpu_eval_batch_size: 4
#learning_rate: 1e-4
# ============= For large model =============
per_gpu_train_batch_size: 1
per_gpu_eval_batch_size: 1
#per_gpu_train_batch_size: 2
#per_gpu_eval_batch_size: 2
learning_rate: 5e-5
gradient_accumulation_steps: 2048
#gradient_accumulation_steps: 128 # For 8bit test only
weight_decay: 0.01
adam_epsilon: 1e-6
adam_betas: "(0.9, 0.999)"
max_grad_norm: 5.0
num_train_epochs: 5
max_steps: 100
warmup_proportion: 0.2
warmup_steps: 0

# Optimizer
optimizer: lamb
use_nvlamb: True

logging_steps: 1
save_steps: 50
eval_steps: 50
no_cuda: True
seed: 42
local_rank: -1
fp16: True
fp16_opt_level: O1

# fairscale.FullyShardedDDP
reshard_after_forward: False
cpu_offload: False
move_grads_to_cpu: False
move_params_to_cpu: False

# Temporary variables
n_gpu:
device:
train_batch_size:
eval_batch_size:

# Notes
note:
