hydra:
  run:
    dir: ./

train_file: LogiQA-dataset/train-reclor-form.json
dev_file: LogiQA-dataset/val-reclor-form.json
test_file: LogiQA-dataset/test-reclor-form.json

# Model
model:
  _target_: models.albert_baseline.AlbertForMultipleChoiceZeroShot.from_pretrained
  mlp_hidden_size: 8192
#  attention_probs_dropout_prob: 0.1
#  hidden_dropout_prob: 0.1
#  fs_checkpoint: True
#  return_dict: False

# Data loading
read_tensor:
  _target_: dataset.reclor_sentence_prefix.convert_examples_into_features
  max_seq_length: 256
  num_workers: 2
  token_num: 5

extended_vocab: ${read_tensor.token_num}

# Data collator
collator:
  _target_: dataset.collators.ReClorSentenceCollator

# Dataloader
num_workers: 4
prefetch_factor: 2

model_name_or_path: experiments/albert.xxlarge.path.v7_v8.2.2.1aug.ctx.TeslaT4/checkpoint-100
pretrain:

#output_dir: experiments/albert.xxlarge.path.v822.1aug.ctx.5.0.w1.TeslaT4.et${read_tensor.token_num}.s${seed}
#output_dir: experiments/albert.xxlarge.path.v822.1aug.ctx.5.0.w1.2080Ti.et${read_tensor.token_num}.s${seed}
#output_dir: experiments/albert.xxlarge.path.v822.1aug.ctx.5.1.w1.2080Ti.et${read_tensor.token_num}.s${seed}
#output_dir: experiments/albert.xxlarge.path.v822.1aug.ctx.5.1.w1.dp0.1.2080Ti.et${read_tensor.token_num}.s${seed}
#output_dir: experiments/albert.xxlarge.path.v822.1aug.ctx.5.1.w2.dp0.1.2080Ti.et${read_tensor.token_num}.s${seed}
#output_dir: experiments/albert.xxlarge.path.v822.1aug.ctx.5.2.w1.2080Ti.et${read_tensor.token_num}.s${seed}
#output_dir: experiments/albert.xxlarge.path.v822.1aug.ctx.5.3.w2.dp0.1.TeslaT4.et${read_tensor.token_num}.s${seed}

#output_dir: experiments/albert.xxlarge.path.v822.1aug.ctx.6.0.w1.TeslaT4.et${read_tensor.token_num}.s${seed}  # batch size = 8
#output_dir: experiments/albert.xxlarge.path.v822.1aug.ctx.6.0.w2.TeslaT4.et${read_tensor.token_num}.s${seed}

output_dir: experiments/albert.logiqa.path.v822.1aug.ctx.5.1.w1.dp0.1.2080Ti.et${read_tensor.token_num}.s${seed}
#output_dir: experiments/albert.logiqa.path.v822.1aug.ctx.5.1.w1.2080Ti.et${read_tensor.token_num}.s${seed}
#output_dir: experiments/albert.logiqa.path.v822.1aug.ctx.5.3.w2.dp0.1.TitanXP.et${read_tensor.token_num}.s${seed}
#output_dir: experiments/albert.logiqa.path.v822.1aug.ctx.5.3.w4.dp0.1.TeslaT4.et${read_tensor.token_num}.s${seed}
#output_dir: experiments/albert.logiqa.path.v822.1aug.ctx.5.3.w1.2080Ti.et${read_tensor.token_num}.s${seed}
#output_dir: experiments/albert.logiqa.path.v822.1aug.ctx.5.3.w1.2080Ti.8bit.et${read_tensor.token_num}.s${seed}

do_train: True
#do_train: False
evaluate_during_training: True

#do_eval: False
do_eval: True
eval_sub_path:

# Training hyper-parameters
per_gpu_train_batch_size: 1
per_gpu_eval_batch_size: 1
#learning_rate: 1e-5
#learning_rate: 8e-6
#learning_rate: 2e-5
learning_rate: 3e-5
gradient_accumulation_steps: 24
#gradient_accumulation_steps: 12
#gradient_accumulation_steps: 6
weight_decay: 0.01
adam_epsilon: 1e-6
adam_betas: "(0.9, 0.98)"
max_grad_norm: 0.0
num_train_epochs: 10
max_steps: 0
warmup_proportion: 0.1
warmup_steps: 0

bit_training: True

logging_steps: 5
save_steps: 100
eval_steps: 100
no_cuda: False
seed: 42
local_rank: -1
fp16: True
fp16_opt_level: O2

# Prediction config
prediction_cfg:
  metric: "acc"
  measure: 1
  best_checkpoint:
  best_result:

# fairscale.FullyShardedDDP
reshard_after_forward: False
cpu_offload: False
move_grads_to_cpu: False
move_params_to_cpu: False

# Temporary variables
n_gpu:
device:
train_batch_size:
eval_batch_size:
world_size:
